### ISSUE TITLE
Error unzipping LookupError: unknown encoding: cp437

### ISSUE THREAD

**Issue by chekmanh** [d-krupke/AlgBench#6]
[03_looking_at_results.pdf](https://github.com/d-krupke/AlgBench/files/12845709/03_looking_at_results.pdf)

Error when running code in jupyter notebook.

**Comment by d-krupke** [comment]
Could you please try the following snippet?

```
import encodings
assert encodings.search_function("cp437") is not None
```

**Comment by chekmanh** [comment]
works fine now

**Comment by d-krupke** [comment]
Bug seems to have been external closing for now because there is nothing I can do to evaluate it.
